version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:8.11.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - logger.level=WARN
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 10s
      timeout: 10s
      retries: 24

  places:
    build: ./Places
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PRJ=Api
    ports:
      - 5789:80
    depends_on:
      elasticsearch:
        condition: service_healthy

  # kibana:
  #   image: kibana:8.11.3
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy

  # distance:
  #   build: ./Distance
  #   environment:
  #     - ASPNETCORE_URLS=http://+:80
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - PRJ=Api
  #   ports:
  #     - 5788:80
  #   depends_on:
  #     - redis