version: '3.8'

services:

  distance:
    build: ./Distance
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PRJ=Api
    ports:
      - 5788:80
    depends_on:
      - redis

  places:
    build: ./Places
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - PRJ=Api
    ports:
      - 5789:80

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.11.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false